export const suspiciousProcesses = [
  'discord',
  'telegram',
  'slack',
  'teams',
  'zoom',
  'skype',
  'whatsapp',
  'viber',
  'signal',
  'element',
  // Browsers
  'chrome',
  'firefox',
  'safari',
  'edge',
  'opera',
  'brave',
  'vivaldi',
  'yandex',
  // AI assistants and chatbots
  'chatgpt',
  'claude',
  'bard',
  'copilot',
  'cluely',
  'coder',
  'codewhisperer',
  'tabnine',
  'kite',
  'aicode',
  'openai',
  'anthropic',
  'huggingface',
  'perplexity',
  'jasper',
  'writesonic',
  'cursor',
  'vscode',
  'intellij',
  // Screen recording and screenshot tools
  'obs',
  'bandicam',
  'camtasia',
  'fraps',
  'xsplit',
  'streamlabs',
  'quicktime',
  'screenflow',
  'snagit',
  'lightshot',
  'gyazo',
  'greenshot',
  'flameshot',
  'shutter',
  'kazam',
  'recordmydesktop',
  'simplescreenrecorder',
  'vokoscreen',
  'peek',
  // Remote access and VNC
  'teamviewer',
  'anydesk',
  'chrome remote',
  'parsec',
  'splashtop',
  'logmein',
  'gotomypc',
  'nomachine',
  'realvnc',
  'tightvnc',
  'ultravnc',
  'x11vnc',
  'remmina',
  'vinagre',
  'krdc',
  'chicken',
  'screens',
  'jump desktop',
  // Virtual machines and containers
  'virtualbox',
  'parallels',
];

export const systemProcessesPatterns = [
  // Windows
  'System',
  'Registry',
  'smss.exe',
  'csrss.exe',
  'wininit.exe',
  'winlogon.exe',
  'services.exe',
  'lsass.exe',
  'svchost.exe',
  'dwm.exe',
  'conhost.exe',
  'fontdrvhost.exe',
  'WmiPrvSE.exe',

  // macOS
  'kernel_task',
  'launchd',
  'kextd',
  'UserEventAgent',
  'cfprefsd',
  'distnoted',
  'syslogd',
  'logd',
  'powerd',
  'bluetoothd',

  // Linux
  'init',
  'kthreadd',
  'ksoftirqd',
  'migration',
  'rcu_',
  'watchdog',
  'systemd',
  'NetworkManager',
  'pulseaudio',
  'dbus',
  'avahi-daemon',

  // Общие паттерны
  '[kworker',
  '[ksoftirqd',
  '[migration',
  '[rcu_',
  '[watchdog',
];
